name: Publish

# Controls when the action will run.
on:
  # Triggers the workflow on new SemVer tags
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    uses: SiaFoundation/workflows/.github/workflows/go-publish.yml@dddded471aae1c7b6f0fbc388d603b8b16336f6f # not on latest because of changes to workflow
    secrets: inherit
    with:
      linux-build-args: -tags=timetzdata -trimpath -a -ldflags '-s -w -linkmode external -extldflags "-static"'
      windows-build-args: -tags=timetzdata -trimpath -a -ldflags '-s -w -linkmode external -extldflags "-static"'
      macos-build-args: -tags=timetzdata -trimpath -a -ldflags '-s -w'
      cgo-enabled: 1
      project: clusterd
      project-desc: "clusterd: A tool for local e2e testing of Sia nodes"
      version-tag: ${{ github.ref_name }}
